### ISSUE TITLE
phoenix data server down?

### ISSUE THREAD

**Issue by cliffnyang** [openeventdata/phoenix_pipeline#100]
i can't access the website to download the data anymore....any idea how soon will it be back up and running?

**Comment by johnb30** [comment]
There was a hardware failure on the server our website was hosted on. Haven't had a chance to boot it back up yet. You should still be able to download the data from the Amazon S3 bucket, though, or by using the URL with the proper date, e.g., https://s3.amazonaws.com/oeda/data/current/events.full.20160724.txt.zip

**Comment by cliffnyang** [comment]
i don't think the s3 url works either....

**Comment by cliffnyang** [comment]
thanks. this works for me. but the 7/22 - 7/24 files are all empty.

**Comment by johnb30** [comment]
Working on regenerating those now.

**Comment by cliffnyang** [comment]
7/25 file is good, but 7/22 - 7/24 are still blank....

**Comment by johnb30** [comment]
Those dates are now filled in as much as they can be.
