### ISSUE TITLE
 [Errno 61] Connection refused)

### ISSUE THREAD

**Issue by dbl001** [openeventdata/phoenix_pipeline#87]
WARNING 2015-08-23 09:28:08,986: There was an error requesting geolocation. HTTPConnectionPool(host='localhost', port=8999): Max retries exceeded with url: /CLIFF-2.0.0/parse/text?q=Argentina%2C+United+States%2C+Chile%2C+Peru%2C+Brazil%2C+England%2C+Germany+and+France+have+all+collaborated+in+this+venture.+ (Caused by <class 'socket.error'>: [Errno 61] Connection refused)

Is this just a timing problem due to a busy server?

**Comment by johnb30** [comment]
You'd need to fire up a CLIFF instance on your local instance to get that to work. You can find some helpful things on that [here](https://github.com/ahalterman/CLIFF-up).

**Comment by dbl001** [comment]
I opted for CLIFF instead of CLIFF-UP because the Virtual Box has a heavy memory requirement (4GB).

CLAVEN built and tested ok, but
CLIFF is getting errors:  Clavin Error opening gazetteer index.

Any ideas?

Failed tests: 
  GeoNameLookupTest.testCountryLookup:16 expected:<0> but was:<250>
  GeoNameLookupTest.testAdm1Lookup:24 expected:<0> but was:<3895>

Tests in error: 
  EntityParserTest.extractAndResolveFromSentences:30 » Clavin Error opening gaze...
  ParseManagerTest.testState:44 NullPointer
  ParseManagerTest.testCity:31 NullPointer
  ParseManagerTest.testCountry:18 NullPointer
  BlacklistTest.testReddit:16 » Clavin Error opening gazetteer index.
  CustomLuceneLocationResolverTest.testGetByGeoNameId:21 » Clavin Error opening ...
  DemonymPlaceTest.testAustralian:35 » Clavin Error opening gazetteer index.
  DemonymPlaceTest.testDemonymInArticle:22 » Clavin Error opening gazetteer inde...
  DemonymPlaceTest.testAmerican:42 » Clavin Error opening gazetteer index.
  DemonymPlaceTest.testIndonesian:49 » Clavin Error opening gazetteer index.
  DemonymPlaceTest.testChinese:28 » Clavin Error opening gazetteer index.
  DemonymPlaceTest.testEuropean:56 » Clavin Error opening gazetteer index.
  DemonymPlaceTest.testAfghanistan:64 » Clavin Error opening gazetteer index.
  AmazonPlaceTest.testAmazon:17 » Clavin Error opening gazetteer index.
  ArlingtonVirginiaPlaceTest.testAbbreviation:27 » Clavin Error opening gazettee...
  AsiaPlaceTest.testAsia:15 » Clavin Error opening gazetteer index.
  BangorMainePlaceTest.testBangorMaine:17 » Clavin Error opening gazetteer index...
  ColomboPlaceTest.testColombo:15 » Clavin Error opening gazetteer index.
  DelawarePlaceTest.testDelawareState:17 » Clavin Error opening gazetteer index.
  DelawarePlaceTest.test10kReportMention:27 » Clavin Error opening gazetteer ind...
  FranceNLPPlaceTest.testFranceFromNlp:28 » Clavin Error opening gazetteer index...
  HandCodedDisambiguationTest.testHuffPoHandCodedArticles:29->verifyArticlesMentionHandCodedCountry:47 » Clavin
  LondonRusselSqPlaceTest.testRussellSq:16 » Clavin Error opening gazetteer inde...
  MiddleEastPlaceTest.testMiddleEastExample:15 » Clavin Error opening gazetteer ...
  MinnesotaPlaceTest.testMinnesotaExample:15 » Clavin Error opening gazetteer in...
  MultiCountryPlaceTest.testCountryExample:15 » Clavin Error opening gazetteer i...
  OklahomaPlaceTest.testOklahoma:17 » Clavin Error opening gazetteer index.
  SantoDomingoPlaceTest.testSantoDomingo:14 » Clavin Error opening gazetteer ind...
  SaoPauloPlaceTest.testSaoPauloAccents:18 » Clavin Error opening gazetteer inde...
  UnitedKingdomPlaceTest.testUkExample:15 » Clavin Error opening gazetteer index...
  UnitedStatesPlaceTest.testUsExample:15 » Clavin Error opening gazetteer index.
  GeoNameAncestryTest.test:22 » NullPointer

Tests run: 48, Failures: 2, Errors: 32, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:38 min
[INFO] Finished at: 2015-08-24T10:43:38-08:00
[INFO] Final Memory: 9M/180M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on project stanford-entity-extractor: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/davidlaxer/CLIFF/stanford-entity-extractor/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
David-Laxers-MacBook-Pro:stanford-entity-extractor davidlaxer$ pwd
/Users/davidlaxer/CLIFF/stanford-entity-extractor
David-Laxers-MacBook-Pro:stanford-entity-extractor davidlaxer$ ls
log	pom.xml	src	target
David-Laxers-MacBook-Pro:stanford-entity-extractor davidlaxer$ vi pom.xml 
David-Laxers-MacBook-Pro:stanford-entity-extractor davidlaxer$ vi ..
David-Laxers-MacBook-Pro:stanford-entity-extractor davidlaxer$ cd ..
David-Laxers-MacBook-Pro:CLIFF davidlaxer$ vi pom.xml
David-Laxers-MacBook-Pro:CLIFF davidlaxer$ cd
David-Laxers-MacBook-Pro:~ davidlaxer$ git clone https://github.com/c4fcm/CLIFF-up.git
Cloning into 'CLIFF-up'...
remote: Counting objects: 101, done.
remote: Total 101 (delta 0), reused 0 (delta 0), pack-reused 101
Receiving objects: 100% (101/101), 138.70 KiB | 0 bytes/s, done.
Resolving deltas: 100% (57/57), done.
Checkin
